<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Data Wrangling | Data-Scientific Programming Notes</title>
  <meta name="description" content="Chapter 2 Data Wrangling | Data-Scientific Programming Notes" />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Data Wrangling | Data-Scientific Programming Notes" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Data Wrangling | Data-Scientific Programming Notes" />
  
  
  

<meta name="author" content="Andrew Sage" />


<meta name="date" content="2022-01-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-visualization.html"/>

<script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data-Scientific Programming Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>1</b> Data Visualization</a><ul>
<li class="chapter" data-level="1.1" data-path="data-visualization.html"><a href="data-visualization.html#loading-and-exploring-data"><i class="fa fa-check"></i><b>1.1</b> Loading and Exploring Data</a><ul>
<li class="chapter" data-level="1.1.1" data-path="data-visualization.html"><a href="data-visualization.html#creating-graphics"><i class="fa fa-check"></i><b>1.1.1</b> Creating Graphics</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.1.1-basic-scatterplot"><i class="fa fa-check"></i>Example 1.1.1 Basic Scatterplot</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.1.2-scatterplot-with-text-labels"><i class="fa fa-check"></i>Example 1.1.2 Scatterplot with text labels</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.1.3-scatterplot-with-color-shape-and-size"><i class="fa fa-check"></i>Example 1.1.3 Scatterplot with color, shape, and size</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.1.4-changing-axis-labels-and-hiding-legend"><i class="fa fa-check"></i>Example 1.1.4 Changing Axis Labels and Hiding Legend</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#practice-1.1.5"><i class="fa fa-check"></i>Practice 1.1.5</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="data-visualization.html"><a href="data-visualization.html#more-graphics"><i class="fa fa-check"></i><b>1.2</b> More Graphics</a><ul>
<li class="chapter" data-level="1.2.1" data-path="data-visualization.html"><a href="data-visualization.html#visualizing-quantitative-data-continued"><i class="fa fa-check"></i><b>1.2.1</b> Visualizing Quantitative Data (Continued)</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.2.1-faceting"><i class="fa fa-check"></i>Example 1.2.1: Faceting</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.2.2-histograms"><i class="fa fa-check"></i>Example 1.2.2: Histograms</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.2.3-boxplots"><i class="fa fa-check"></i>Example 1.2.3: Boxplots</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#practice-1.2.4"><i class="fa fa-check"></i>Practice 1.2.4</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#practice-1.2.5"><i class="fa fa-check"></i>Practice 1.2.5</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#practice-1.2.6"><i class="fa fa-check"></i>Practice 1.2.6</a></li>
<li class="chapter" data-level="1.2.2" data-path="data-visualization.html"><a href="data-visualization.html#visualizing-categorical-data"><i class="fa fa-check"></i><b>1.2.2</b> Visualizing Categorical Data</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.2.7-bar-graph"><i class="fa fa-check"></i>Example 1.2.7: Bar Graph</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.2.8-reordering-bars"><i class="fa fa-check"></i>Example 1.2.8 Reordering Bars</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.2.9-relative-frequency-bar-graph"><i class="fa fa-check"></i>Example 1.2.9 Relative Frequency Bar Graph</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#practice-1.2.10"><i class="fa fa-check"></i>Practice 1.2.10</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#practice-1.2.11"><i class="fa fa-check"></i>Practice 1.2.11</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#practice-1.2.12"><i class="fa fa-check"></i>Practice 1.2.12</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.2.13-stacked-bar-graph"><i class="fa fa-check"></i>Example 1.2.13 Stacked Bar Graph</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.2.14-stacked-bar-graph-with-equal-heights"><i class="fa fa-check"></i>Example 1.2.14 Stacked Bar Graph with Equal Heights</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.2.15-side-by-side-bar-graph"><i class="fa fa-check"></i>Example 1.2.15 Side-by-Side Bar Graph</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.2.16-height-specified-by-variable"><i class="fa fa-check"></i>Example 1.2.16 Height Specified by Variable</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#practice-1.2.17-height-specified-by-variable"><i class="fa fa-check"></i>Practice 1.2.17 Height Specified by Variable</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="data-visualization.html"><a href="data-visualization.html#advanced-data-graphics"><i class="fa fa-check"></i><b>1.3</b> Advanced Data Graphics</a><ul>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#babynames-dataset"><i class="fa fa-check"></i>Babynames dataset</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.3.1-age-distribution-for-a-given-name"><i class="fa fa-check"></i>Example 1.3.1: Age Distribution for a Given Name</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#choosing-name-and-gender"><i class="fa fa-check"></i>Choosing Name and Gender</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#setting-axis-limits"><i class="fa fa-check"></i>Setting Axis Limits</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#adding-line"><i class="fa fa-check"></i>Adding Line</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#axis-labels"><i class="fa fa-check"></i>Axis Labels</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#adding-text"><i class="fa fa-check"></i>Adding Text</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#adding-median-age"><i class="fa fa-check"></i>Adding Median Age</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#example-1.3.2-common-female-names"><i class="fa fa-check"></i>Example 1.3.2: Common Female Names</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#some-data-prep"><i class="fa fa-check"></i>Some data prep</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#setup-the-plot"><i class="fa fa-check"></i>Setup the Plot</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#add-linerange-and-color"><i class="fa fa-check"></i>Add Linerange and color</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#add-points-at-median"><i class="fa fa-check"></i>Add points at median</a></li>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#add-labels-and-flip-coordinates"><i class="fa fa-check"></i>Add Labels and Flip Coordinates</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i><b>2</b> Data Wrangling</a><ul>
<li class="chapter" data-level="2.1" data-path="data-wrangling.html"><a href="data-wrangling.html#filtering-and-arranging-data-and-selecting-columns"><i class="fa fa-check"></i><b>2.1</b> Filtering and Arranging Data, and Selecting Columns</a><ul>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.1.1"><i class="fa fa-check"></i>Example 2.1.1</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.1.2"><i class="fa fa-check"></i>Example 2.1.2</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.1.3"><i class="fa fa-check"></i>Example 2.1.3</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.1.4"><i class="fa fa-check"></i>Example 2.1.4</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.1.5"><i class="fa fa-check"></i>Example 2.1.5</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#practice-2.1.6"><i class="fa fa-check"></i>Practice 2.1.6</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#practice-2.1.7"><i class="fa fa-check"></i>Practice 2.1.7</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#practice-2.1.8"><i class="fa fa-check"></i>Practice 2.1.8</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.1.9-multiple-logicals"><i class="fa fa-check"></i>Example 2.1.9 Multiple Logicals</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.1.10-dealing-with-nas"><i class="fa fa-check"></i>Example 2.1.10: Dealing with NA's</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#practice-2.1.11"><i class="fa fa-check"></i>Practice 2.1.11</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#practice-2.1.12"><i class="fa fa-check"></i>Practice 2.1.12</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="data-wrangling.html"><a href="data-wrangling.html#section-2.2-mutating-summarizing-and-grouping-data"><i class="fa fa-check"></i><b>2.2</b> Section 2.2 Mutating, Summarizing, and Grouping Data</a><ul>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.2.1"><i class="fa fa-check"></i>Example 2.2.1</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.2.2"><i class="fa fa-check"></i>Example 2.2.2</a></li>
<li class="chapter" data-level="2.2.1" data-path="data-wrangling.html"><a href="data-wrangling.html#summarize"><i class="fa fa-check"></i><b>2.2.1</b> Summarize</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.2.3"><i class="fa fa-check"></i>Example 2.2.3</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#practice-2.2.4"><i class="fa fa-check"></i>Practice 2.2.4</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#practice-2.2.5"><i class="fa fa-check"></i>Practice 2.2.5</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.2.6"><i class="fa fa-check"></i>Example 2.2.6</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.2.7"><i class="fa fa-check"></i>Example 2.2.7</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.2.8"><i class="fa fa-check"></i>Example 2.2.8</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#example-2.2.9"><i class="fa fa-check"></i>Example 2.2.9</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#practice-2.2.10"><i class="fa fa-check"></i>Practice 2.2.10</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#practice-2.2.11"><i class="fa fa-check"></i>Practice 2.2.11</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#practice-2.2.12"><i class="fa fa-check"></i>Practice 2.2.12</a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#practice-2.2.13"><i class="fa fa-check"></i>Practice 2.2.13</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data-Scientific Programming Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-wrangling" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Data Wrangling</h1>
<p>These notes pertain to chapter 5 in Wickham and Grolemund's text. We'll consider data from Major League Baseball, available through the <code>Lahman()</code> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(Lahman)
select &lt;-<span class="st"> </span>dplyr<span class="op">::</span>select
summarize &lt;-<span class="st"> </span>dplyr<span class="op">::</span>summarize</code></pre></div>
<p>We create a tibble with batting records for all MLB players from 1871-2020</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(Lahman<span class="op">::</span>Batting)
<span class="kw">head</span>(batting)</code></pre></div>
<pre><code>## # A tibble: 6 x 22
##   playerID  yearID stint teamID lgID      G    AB     R     H   X2B   X3B    HR
##   &lt;chr&gt;      &lt;int&gt; &lt;int&gt; &lt;fct&gt;  &lt;fct&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1 abercda01   1871     1 TRO    NA        1     4     0     0     0     0     0
## 2 addybo01    1871     1 RC1    NA       25   118    30    32     6     0     0
## 3 allisar01   1871     1 CL1    NA       29   137    28    40     4     5     0
## 4 allisdo01   1871     1 WS3    NA       27   133    28    44    10     2     2
## 5 ansonca01   1871     1 RC1    NA       25   120    29    39    11     3     0
## 6 armstbo01   1871     1 FW1    NA       12    49     9    11     2     1     0
## # … with 10 more variables: RBI &lt;int&gt;, SB &lt;int&gt;, CS &lt;int&gt;, BB &lt;int&gt;, SO &lt;int&gt;,
## #   IBB &lt;int&gt;, HBP &lt;int&gt;, SH &lt;int&gt;, SF &lt;int&gt;, GIDP &lt;int&gt;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tail</span>(batting)</code></pre></div>
<pre><code>## # A tibble: 6 x 22
##   playerID  yearID stint teamID lgID      G    AB     R     H   X2B   X3B    HR
##   &lt;chr&gt;      &lt;int&gt; &lt;int&gt; &lt;fct&gt;  &lt;fct&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1 zimmebr01   2020     1 CLE    AL       20    37     3     6     0     0     1
## 2 zimmebr02   2020     1 BAL    AL        2     0     0     0     0     0     0
## 3 zimmejo02   2020     1 DET    AL        3     0     0     0     0     0     0
## 4 zimmeky01   2020     1 KCA    AL       16     0     0     0     0     0     0
## 5 zuberty01   2020     1 KCA    AL       23     0     0     0     0     0     0
## 6 zuninmi01   2020     1 TBA    AL       28    75     8    11     4     0     4
## # … with 10 more variables: RBI &lt;int&gt;, SB &lt;int&gt;, CS &lt;int&gt;, BB &lt;int&gt;, SO &lt;int&gt;,
## #   IBB &lt;int&gt;, HBP &lt;int&gt;, SH &lt;int&gt;, SF &lt;int&gt;, GIDP &lt;int&gt;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(batting)</code></pre></div>
<pre><code>##    playerID             yearID         stint           teamID      lgID      
##  Length:108789      Min.   :1871   Min.   :1.000   CHN    : 5060   AA: 1893  
##  Class :character   1st Qu.:1937   1st Qu.:1.000   PHI    : 4971   AL:50133  
##  Mode  :character   Median :1976   Median :1.000   PIT    : 4920   FL:  472  
##                     Mean   :1967   Mean   :1.079   SLN    : 4853   NA:  737  
##                     3rd Qu.:2001   3rd Qu.:1.000   CIN    : 4731   NL:55071  
##                     Max.   :2020   Max.   :5.000   CLE    : 4683   PL:  149  
##                                                    (Other):79571   UA:  334  
##        G                AB              R                H         
##  Min.   :  1.00   Min.   :  0.0   Min.   :  0.00   Min.   :  0.00  
##  1st Qu.: 12.00   1st Qu.:  4.0   1st Qu.:  0.00   1st Qu.:  0.00  
##  Median : 34.00   Median : 46.0   Median :  4.00   Median :  8.00  
##  Mean   : 50.74   Mean   :139.2   Mean   : 18.48   Mean   : 36.39  
##  3rd Qu.: 79.00   3rd Qu.:224.0   3rd Qu.: 27.00   3rd Qu.: 56.00  
##  Max.   :165.00   Max.   :716.0   Max.   :198.00   Max.   :262.00  
##                                                                    
##       X2B              X3B               HR             RBI        
##  Min.   : 0.000   Min.   : 0.000   Min.   : 0.00   Min.   :  0.00  
##  1st Qu.: 0.000   1st Qu.: 0.000   1st Qu.: 0.00   1st Qu.:  0.00  
##  Median : 1.000   Median : 0.000   Median : 0.00   Median :  3.00  
##  Mean   : 6.202   Mean   : 1.247   Mean   : 2.85   Mean   : 16.79  
##  3rd Qu.: 9.000   3rd Qu.: 1.000   3rd Qu.: 2.00   3rd Qu.: 24.00  
##  Max.   :67.000   Max.   :36.000   Max.   :73.00   Max.   :191.00  
##                                                    NA&#39;s   :756     
##        SB                CS               BB               SO        
##  Min.   :  0.000   Min.   : 0.000   Min.   :  0.00   Min.   :  0.00  
##  1st Qu.:  0.000   1st Qu.: 0.000   1st Qu.:  0.00   1st Qu.:  1.00  
##  Median :  0.000   Median : 0.000   Median :  2.00   Median :  9.00  
##  Mean   :  2.919   Mean   : 1.177   Mean   : 12.84   Mean   : 20.56  
##  3rd Qu.:  2.000   3rd Qu.: 1.000   3rd Qu.: 18.00   3rd Qu.: 29.00  
##  Max.   :138.000   Max.   :42.000   Max.   :232.00   Max.   :223.00  
##  NA&#39;s   :2368      NA&#39;s   :23541                     NA&#39;s   :2100    
##       IBB              HBP               SH               SF       
##  Min.   :  0.00   Min.   : 0.000   Min.   : 0.000   Min.   : 0.00  
##  1st Qu.:  0.00   1st Qu.: 0.000   1st Qu.: 0.000   1st Qu.: 0.00  
##  Median :  0.00   Median : 0.000   Median : 0.000   Median : 0.00  
##  Mean   :  1.06   Mean   : 1.058   Mean   : 2.197   Mean   : 1.02  
##  3rd Qu.:  1.00   3rd Qu.: 1.000   3rd Qu.: 3.000   3rd Qu.: 1.00  
##  Max.   :120.00   Max.   :51.000   Max.   :67.000   Max.   :19.00  
##  NA&#39;s   :36650    NA&#39;s   :2816     NA&#39;s   :6068     NA&#39;s   :36103  
##       GIDP       
##  Min.   : 0.000  
##  1st Qu.: 0.000  
##  Median : 0.000  
##  Mean   : 2.893  
##  3rd Qu.: 4.000  
##  Max.   :36.000  
##  NA&#39;s   :25441</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(batting)</code></pre></div>
<pre><code>## [1] 108789     22</code></pre>
<div id="filtering-and-arranging-data-and-selecting-columns" class="section level2">
<h2><span class="header-section-number">2.1</span> Filtering and Arranging Data, and Selecting Columns</h2>
<p>The <code>filter()</code> command narrows a dataset to rows that meet a specified condition.</p>
<p>The <code>arrange()</code> command sorts a dataset according to a specified ordering.</p>
<p>The <code>select()</code> command narrows a dataset to a specified set of columns</p>
<p>These commands are part of the <code>dplyr</code> R package, which itself is part of <code>tidyverse</code>.</p>
<div id="example-2.1.1" class="section level3 unnumbered">
<h3>Example 2.1.1</h3>
<p>Using the baseball data, create a tibble with only data from the most recent season available (2020).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting2020 &lt;-<span class="st"> </span>batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(yearID <span class="op">==</span><span class="st"> </span><span class="dv">2020</span>)
<span class="kw">head</span>(batting2020)</code></pre></div>
<pre><code>## # A tibble: 6 x 22
##   playerID  yearID stint teamID lgID      G    AB     R     H   X2B   X3B    HR
##   &lt;chr&gt;      &lt;int&gt; &lt;int&gt; &lt;fct&gt;  &lt;fct&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1 abreual01   2020     1 NYA    AL        2     0     0     0     0     0     0
## 2 abreubr01   2020     1 HOU    AL        4     0     0     0     0     0     0
## 3 abreujo02   2020     1 CHA    AL       60   240    43    76    15     0    19
## 4 acunaro01   2020     1 ATL    NL       46   160    46    40    11     0    14
## 5 adamewi01   2020     1 TBA    AL       54   185    29    48    15     1     8
## 6 adamja01    2020     1 CHN    NL       13     0     0     0     0     0     0
## # … with 10 more variables: RBI &lt;int&gt;, SB &lt;int&gt;, CS &lt;int&gt;, BB &lt;int&gt;, SO &lt;int&gt;,
## #   IBB &lt;int&gt;, HBP &lt;int&gt;, SH &lt;int&gt;, SF &lt;int&gt;, GIDP &lt;int&gt;</code></pre>
<p>An equivalent way to do this is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting2020 &lt;-<span class="st"> </span><span class="kw">filter</span>(batting, yearID <span class="op">==</span><span class="st"> </span><span class="dv">2020</span>)
<span class="kw">head</span>(batting2020)</code></pre></div>
<pre><code>## # A tibble: 6 x 22
##   playerID  yearID stint teamID lgID      G    AB     R     H   X2B   X3B    HR
##   &lt;chr&gt;      &lt;int&gt; &lt;int&gt; &lt;fct&gt;  &lt;fct&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1 abreual01   2020     1 NYA    AL        2     0     0     0     0     0     0
## 2 abreubr01   2020     1 HOU    AL        4     0     0     0     0     0     0
## 3 abreujo02   2020     1 CHA    AL       60   240    43    76    15     0    19
## 4 acunaro01   2020     1 ATL    NL       46   160    46    40    11     0    14
## 5 adamewi01   2020     1 TBA    AL       54   185    29    48    15     1     8
## 6 adamja01    2020     1 CHN    NL       13     0     0     0     0     0     0
## # … with 10 more variables: RBI &lt;int&gt;, SB &lt;int&gt;, CS &lt;int&gt;, BB &lt;int&gt;, SO &lt;int&gt;,
## #   IBB &lt;int&gt;, HBP &lt;int&gt;, SH &lt;int&gt;, SF &lt;int&gt;, GIDP &lt;int&gt;</code></pre>
<p>We'll use the first way, though. The %&gt;% operator (called <strong>pipe</strong>) has advantages and makes coding more convenient when stringing together multiple operations.</p>
</div>
<div id="example-2.1.2" class="section level3 unnumbered">
<h3>Example 2.1.2</h3>
<p>Create a tibble including only players who played for teams currently in the National League Central division: Milwaukee (MIL), Chicago Cubs (CHN), Pittsburgh (PIT), Cincinnati (CIN), and St. Louis (SLN).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting_NLCentral &lt;-<span class="st"> </span>batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(teamID <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;MIL&quot;</span>, <span class="st">&quot;CHN&quot;</span>, <span class="st">&quot;PIT&quot;</span>, <span class="st">&quot;CIN&quot;</span>, <span class="st">&quot;SNL&quot;</span>))
<span class="kw">head</span>(batting_NLCentral)</code></pre></div>
<pre><code>## # A tibble: 6 x 22
##   playerID  yearID stint teamID lgID      G    AB     R     H   X2B   X3B    HR
##   &lt;chr&gt;      &lt;int&gt; &lt;int&gt; &lt;fct&gt;  &lt;fct&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1 addybo01    1876     1 CHN    NL       32   142    36    40     4     1     0
## 2 andrufr01   1876     1 CHN    NL        8    36     6    11     3     0     0
## 3 ansonca01   1876     1 CHN    NL       66   309    63   110     9     7     2
## 4 barnero01   1876     1 CHN    NL       66   322   126   138    21    14     1
## 5 bielaos01   1876     1 CHN    NL       32   139    24    29     3     0     0
## 6 glennjo01   1876     1 CHN    NL       66   276    55    84     9     2     0
## # … with 10 more variables: RBI &lt;int&gt;, SB &lt;int&gt;, CS &lt;int&gt;, BB &lt;int&gt;, SO &lt;int&gt;,
## #   IBB &lt;int&gt;, HBP &lt;int&gt;, SH &lt;int&gt;, SF &lt;int&gt;, GIDP &lt;int&gt;</code></pre>
</div>
<div id="example-2.1.3" class="section level3 unnumbered">
<h3>Example 2.1.3</h3>
<p>Order the entire baseball tibble from most homeruns to fewest.</p>
<p>Note: we use <code>desc()</code> to sort in descending order. To sort in ascending order, simply put the name of the variable, i.e. <code>HR</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(<span class="kw">desc</span>(HR))</code></pre></div>
<pre><code>## # A tibble: 108,789 x 22
##    playerID  yearID stint teamID lgID      G    AB     R     H   X2B   X3B    HR
##    &lt;chr&gt;      &lt;int&gt; &lt;int&gt; &lt;fct&gt;  &lt;fct&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1 bondsba01   2001     1 SFN    NL      153   476   129   156    32     2    73
##  2 mcgwima01   1998     1 SLN    NL      155   509   130   152    21     0    70
##  3 sosasa01    1998     1 CHN    NL      159   643   134   198    20     0    66
##  4 mcgwima01   1999     1 SLN    NL      153   521   118   145    21     1    65
##  5 sosasa01    2001     1 CHN    NL      160   577   146   189    34     5    64
##  6 sosasa01    1999     1 CHN    NL      162   625   114   180    24     2    63
##  7 marisro01   1961     1 NYA    AL      161   590   132   159    16     4    61
##  8 ruthba01    1927     1 NYA    AL      151   540   158   192    29     8    60
##  9 ruthba01    1921     1 NYA    AL      152   540   177   204    44    16    59
## 10 stantmi03   2017     1 MIA    NL      159   597   123   168    32     0    59
## # … with 108,779 more rows, and 10 more variables: RBI &lt;int&gt;, SB &lt;int&gt;,
## #   CS &lt;int&gt;, BB &lt;int&gt;, SO &lt;int&gt;, IBB &lt;int&gt;, HBP &lt;int&gt;, SH &lt;int&gt;, SF &lt;int&gt;,
## #   GIDP &lt;int&gt;</code></pre>
</div>
<div id="example-2.1.4" class="section level3 unnumbered">
<h3>Example 2.1.4</h3>
<p>Create a tibble that contains only the columns <code>playerID</code>, <code>yearID</code>, <code>teamID</code>, <code>AB</code>, <code>H</code>, and <code>HR</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting1 &lt;-<span class="st"> </span>batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(playerID, yearID, teamID, AB, H, HR)
<span class="kw">head</span>(batting1)</code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   playerID  yearID teamID    AB     H    HR
##   &lt;chr&gt;      &lt;int&gt; &lt;fct&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1 abercda01   1871 TRO        4     0     0
## 2 addybo01    1871 RC1      118    32     0
## 3 allisar01   1871 CL1      137    40     0
## 4 allisdo01   1871 WS3      133    44     2
## 5 ansonca01   1871 RC1      120    39     0
## 6 armstbo01   1871 FW1       49    11     0</code></pre>
</div>
<div id="example-2.1.5" class="section level3 unnumbered">
<h3>Example 2.1.5</h3>
<p>The <code>%&gt;%</code> (pipe) operator allows us to string together multiple commands.</p>
<p>Create a tibble including only players who batted at least 500 times in a season and played for Milwaukee (MIL) during or after the 2000 season. Include the columns <code>playerID</code>, <code>yearID</code>, and <code>RBI</code>, and order the players by most RBI to fewest.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting_MIL &lt;-<span class="st"> </span>batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(teamID <span class="op">==</span><span class="st"> &quot;MIL&quot;</span> <span class="op">&amp;</span><span class="st"> </span>yearID <span class="op">&gt;=</span><span class="st"> </span><span class="dv">2000</span>) <span class="op">%&gt;%</span>
<span class="st">              </span><span class="kw">select</span>(playerID, yearID, RBI) <span class="op">%&gt;%</span>
<span class="st">              </span><span class="kw">arrange</span>(<span class="kw">desc</span>(RBI))
<span class="kw">head</span>(batting_MIL)</code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   playerID  yearID   RBI
##   &lt;chr&gt;      &lt;int&gt; &lt;int&gt;
## 1 fieldpr01   2009   141
## 2 sexsori01   2001   125
## 3 sexsori01   2003   124
## 4 fieldpr01   2011   120
## 5 fieldpr01   2007   119
## 6 leeca01     2005   114</code></pre>
</div>
<div id="practice-2.1.6" class="section level3 unnumbered">
<h3>Practice 2.1.6</h3>
<p>Create a subset of the data that includes only players who played in the American League (AL) after 1950.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Type code here</span></code></pre></div>
</div>
<div id="practice-2.1.7" class="section level3 unnumbered">
<h3>Practice 2.1.7</h3>
<p>Create a tibble containing all players, but only the variables <code>playerID</code>, <code>yearID</code>, &quot;G&quot;, &quot;H&quot;, and &quot;HR&quot;.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Type code here</span></code></pre></div>
</div>
<div id="practice-2.1.8" class="section level3 unnumbered">
<h3>Practice 2.1.8</h3>
<p>Order the rows from most hits in a season to fewest.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Type code here</span></code></pre></div>
</div>
<div id="example-2.1.9-multiple-logicals" class="section level3 unnumbered">
<h3>Example 2.1.9 Multiple Logicals</h3>
<p>The current Washington Nationals franchise previously played in Montreal from 1969-2004, and was known as the Expos. Create a dataset containing statistics for this franchise, including both its time in Montreal, and Washington. Arrange in descending order by number of homeruns.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting_MON_WAS &lt;-<span class="st"> </span>batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>( (teamID<span class="op">==</span><span class="st">&quot;MON&quot;</span> <span class="op">&amp;</span><span class="st"> </span>yearID <span class="op">&gt;=</span><span class="st"> </span><span class="dv">1969</span> <span class="op">&amp;</span><span class="st"> </span>yearID <span class="op">&lt;=</span><span class="st"> </span><span class="dv">2004</span>)
                         <span class="op">|</span><span class="st"> </span>(teamID<span class="op">==</span><span class="st">&quot;WAS&quot;</span> <span class="op">&amp;</span><span class="st"> </span>yearID <span class="op">&gt;=</span><span class="st"> </span><span class="dv">2005</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(<span class="kw">desc</span>(HR))
batting_MON_WAS</code></pre></div>
<pre><code>## # A tibble: 2,242 x 22
##    playerID  yearID stint teamID lgID      G    AB     R     H   X2B   X3B    HR
##    &lt;chr&gt;      &lt;int&gt; &lt;int&gt; &lt;fct&gt;  &lt;fct&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1 soriaal01   2006     1 WAS    NL      159   647   119   179    41     2    46
##  2 guerrvl01   2000     1 MON    NL      154   571   101   197    28    11    44
##  3 guerrvl01   1999     1 MON    NL      160   610   102   193    37     5    42
##  4 harpebr03   2015     1 WAS    NL      153   521   118   172    38     1    42
##  5 guerrvl01   2002     1 MON    NL      161   614   106   206    37     2    39
##  6 guerrvl01   1998     1 MON    NL      159   623   108   202    37     7    38
##  7 dunnad01    2009     1 WAS    NL      159   546    81   146    29     0    38
##  8 dunnad01    2010     1 WAS    NL      158   558    85   145    36     2    38
##  9 rodrihe02   1996     1 MON    NL      145   532    81   147    42     1    36
## 10 zimmery01   2017     1 WAS    NL      144   524    90   159    33     0    36
## # … with 2,232 more rows, and 10 more variables: RBI &lt;int&gt;, SB &lt;int&gt;, CS &lt;int&gt;,
## #   BB &lt;int&gt;, SO &lt;int&gt;, IBB &lt;int&gt;, HBP &lt;int&gt;, SH &lt;int&gt;, SF &lt;int&gt;, GIDP &lt;int&gt;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(batting_MON_WAS)</code></pre></div>
<pre><code>## # A tibble: 6 x 22
##   playerID  yearID stint teamID lgID      G    AB     R     H   X2B   X3B    HR
##   &lt;chr&gt;      &lt;int&gt; &lt;int&gt; &lt;fct&gt;  &lt;fct&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1 soriaal01   2006     1 WAS    NL      159   647   119   179    41     2    46
## 2 guerrvl01   2000     1 MON    NL      154   571   101   197    28    11    44
## 3 guerrvl01   1999     1 MON    NL      160   610   102   193    37     5    42
## 4 harpebr03   2015     1 WAS    NL      153   521   118   172    38     1    42
## 5 guerrvl01   2002     1 MON    NL      161   614   106   206    37     2    39
## 6 guerrvl01   1998     1 MON    NL      159   623   108   202    37     7    38
## # … with 10 more variables: RBI &lt;int&gt;, SB &lt;int&gt;, CS &lt;int&gt;, BB &lt;int&gt;, SO &lt;int&gt;,
## #   IBB &lt;int&gt;, HBP &lt;int&gt;, SH &lt;int&gt;, SF &lt;int&gt;, GIDP &lt;int&gt;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tail</span>(batting_MON_WAS)</code></pre></div>
<pre><code>## # A tibble: 6 x 22
##   playerID  yearID stint teamID lgID      G    AB     R     H   X2B   X3B    HR
##   &lt;chr&gt;      &lt;int&gt; &lt;int&gt; &lt;fct&gt;  &lt;fct&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1 romerse01   2020     1 WAS    NL        3     0     0     0     0     0     0
## 2 sanchan01   2020     1 WAS    NL       11     0     0     0     0     0     0
## 3 scherma01   2020     1 WAS    NL       12     0     0     0     0     0     0
## 4 strasst01   2020     1 WAS    NL        2     0     0     0     0     0     0
## 5 suerowa01   2020     1 WAS    NL       22     0     0     0     0     0     0
## 6 vothau01    2020     1 WAS    NL       11     0     0     0     0     0     0
## # … with 10 more variables: RBI &lt;int&gt;, SB &lt;int&gt;, CS &lt;int&gt;, BB &lt;int&gt;, SO &lt;int&gt;,
## #   IBB &lt;int&gt;, HBP &lt;int&gt;, SH &lt;int&gt;, SF &lt;int&gt;, GIDP &lt;int&gt;</code></pre>
</div>
<div id="example-2.1.10-dealing-with-nas" class="section level3 unnumbered">
<h3>Example 2.1.10: Dealing with NA's</h3>
<p>For some batters, stolen base data (SB) were not available. Filter the dataset to only include rows for which stolen base data were available.</p>
<p>The <code>is.na()</code> command returns TRUE/FALSE depending on whether the value is missing(NA). Here we use the negation operator <code>!</code>, since we want the rows that are not na's.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">battingSB &lt;-<span class="st"> </span>batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(SB))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(battingSB)</code></pre></div>
<pre><code>## [1] 106421     22</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(batting)</code></pre></div>
<pre><code>## [1] 108789     22</code></pre>
</div>
<div id="practice-2.1.11" class="section level3 unnumbered">
<h3>Practice 2.1.11</h3>
<p>Create a tibble that contains only players who played in every one of their team's games in a season. Only consider seasons from 1904 on, since season length was highly variable prior to 1904.</p>
<p>Note that beginning in 1904, teams played 154 games per season. In 1961, the American League (AL) expanded to 162 games. The National League expanded to 162 games in 1962. From 1962-2019, teams played 162 games per season. In 2020, teams only played 60 games, due to covid-19.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Enter code here</span></code></pre></div>
</div>
<div id="practice-2.1.12" class="section level3 unnumbered">
<h3>Practice 2.1.12</h3>
<p>Create a tibble that contains only players who played for Milwaukee in 2020, but contains statistics from all years in these player's careers, whether or not they played for Milwaukee.</p>
<p>For example since Christian Yelich played for Milwaukee in 2020, all of his seasons should be included in the dataset, including 2013-2017, when he did not play for Milwaukee.</p>
<p>Include the variables <code>playerID</code>, <code>yearID</code>, <code>teamID</code>, <code>AB</code>, <code>H</code>, and <code>HR</code>, and order the dataframe in descending order by homeruns (HR).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Enter code here</span></code></pre></div>
</div>
</div>
<div id="section-2.2-mutating-summarizing-and-grouping-data" class="section level2">
<h2><span class="header-section-number">2.2</span> Section 2.2 Mutating, Summarizing, and Grouping Data</h2>
<p>The <code>mutate</code> and <code>transmute</code> functions allow us to create new variables in a dataset from old ones.</p>
<div id="example-2.2.1" class="section level3 unnumbered">
<h3>Example 2.2.1</h3>
<p>A player's <strong>batting average</strong> is defined as number of hits (H) divided by number of at-bats (AB).</p>
<p>A player's <strong>on-base percentage</strong> is defined as number of hits (H), walks (BB), times hit by pitch (HBP), divided by number of at-bats, walks, times hit by pitch, and sacrifice flies (SF).</p>
<p>A player's slugging percentage is defined as singles + 2doubles (X2B) + 3 triples (X3B) + 4 homeruns (HR) divided by number of at-bats.</p>
<p>We'll create each of these variables. Note that since singles is not a variable in the dataset, we'll create it by subtracting doubles, triples, and homeruns from hits.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">AVG =</span> H <span class="op">/</span><span class="st"> </span>AB,
                                  <span class="dt">OBP =</span> (H <span class="op">+</span><span class="st"> </span>BB <span class="op">+</span><span class="st"> </span>HBP) <span class="op">/</span><span class="st"> </span>(AB <span class="op">+</span><span class="st"> </span>BB <span class="op">+</span><span class="st"> </span>HBP <span class="op">+</span>SF),
                                  <span class="dt">X1B =</span> H <span class="op">-</span><span class="st"> </span>X2B <span class="op">-</span><span class="st"> </span>X3B <span class="op">-</span><span class="st"> </span>HR,
                                  <span class="dt">SLG =</span> (X1B <span class="op">+</span><span class="st"> </span><span class="dv">2</span><span class="op">*</span>X2B <span class="op">+</span><span class="st"> </span><span class="dv">3</span><span class="op">*</span>X3B <span class="op">+</span><span class="st"> </span><span class="dv">4</span><span class="op">*</span><span class="st"> </span>HR) <span class="op">/</span><span class="st"> </span>AB) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(playerID, yearID, teamID, AB, H, HR, BB, HBP, SF, AVG, OBP, SLG)</code></pre></div>
<pre><code>## # A tibble: 108,789 x 12
##    playerID  yearID teamID    AB     H    HR    BB   HBP    SF   AVG   OBP   SLG
##    &lt;chr&gt;      &lt;int&gt; &lt;fct&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 abercda01   1871 TRO        4     0     0     0    NA    NA 0        NA 0    
##  2 addybo01    1871 RC1      118    32     0     4    NA    NA 0.271    NA 0.322
##  3 allisar01   1871 CL1      137    40     0     2    NA    NA 0.292    NA 0.394
##  4 allisdo01   1871 WS3      133    44     2     0    NA    NA 0.331    NA 0.481
##  5 ansonca01   1871 RC1      120    39     0     2    NA    NA 0.325    NA 0.467
##  6 armstbo01   1871 FW1       49    11     0     0    NA    NA 0.224    NA 0.306
##  7 barkeal01   1871 RC1        4     1     0     1    NA    NA 0.25     NA 0.25 
##  8 barnero01   1871 BS1      157    63     0    13    NA    NA 0.401    NA 0.580
##  9 barrebi01   1871 FW1        5     1     0     0    NA    NA 0.2      NA 0.4  
## 10 barrofr01   1871 BS1       86    13     0     0    NA    NA 0.151    NA 0.198
## # … with 108,779 more rows</code></pre>
<p>While <code>mutate</code> displays all variables in the dataset, <code>transmute</code> displays only the ones created.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">transmute</span>(<span class="dt">AVG =</span> H <span class="op">/</span><span class="st"> </span>AB,
                                  <span class="dt">OBP =</span> (H <span class="op">+</span><span class="st"> </span>BB <span class="op">+</span><span class="st"> </span>HBP) <span class="op">/</span><span class="st"> </span>(AB <span class="op">+</span><span class="st"> </span>BB <span class="op">+</span><span class="st"> </span>HBP <span class="op">+</span>SF),
                                  <span class="dt">X1B =</span> H <span class="op">-</span><span class="st"> </span>X2B <span class="op">-</span><span class="st"> </span>X3B <span class="op">-</span><span class="st"> </span>HR,
                                  <span class="dt">SLG =</span> (X1B <span class="op">+</span><span class="st"> </span><span class="dv">2</span><span class="op">*</span>X2B <span class="op">+</span><span class="st"> </span><span class="dv">3</span><span class="op">*</span>X3B <span class="op">+</span><span class="st"> </span><span class="dv">4</span><span class="op">*</span><span class="st"> </span>HR) <span class="op">/</span><span class="st"> </span>AB) </code></pre></div>
<pre><code>## # A tibble: 108,789 x 4
##      AVG   OBP   X1B   SLG
##    &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt;
##  1 0        NA     0 0    
##  2 0.271    NA    26 0.322
##  3 0.292    NA    31 0.394
##  4 0.331    NA    30 0.481
##  5 0.325    NA    25 0.467
##  6 0.224    NA     8 0.306
##  7 0.25     NA     1 0.25 
##  8 0.401    NA    44 0.580
##  9 0.2      NA     0 0.4  
## 10 0.151    NA    10 0.198
## # … with 108,779 more rows</code></pre>
</div>
<div id="example-2.2.2" class="section level3 unnumbered">
<h3>Example 2.2.2</h3>
<p>Create a new variable that indicates whether or not a player played for a team currently in the National League Central Division (MIL, CIN, CHN, CIN, PIT).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">NLCentral =</span> <span class="kw">ifelse</span>(teamID <span class="op">%in%</span><span class="kw">c</span>(<span class="st">&quot;MIL&quot;</span>, <span class="st">&quot;CIN&quot;</span>, <span class="st">&quot;CHN&quot;</span>, <span class="st">&quot;CIN&quot;</span>, <span class="st">&quot;PIT&quot;</span>), <span class="st">&quot;Yes&quot;</span>, <span class="st">&quot;No&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(playerID,  yearID, teamID, NLCentral)</code></pre></div>
<pre><code>## # A tibble: 108,789 x 4
##    playerID  yearID teamID NLCentral
##    &lt;chr&gt;      &lt;int&gt; &lt;fct&gt;  &lt;chr&gt;    
##  1 abercda01   1871 TRO    No       
##  2 addybo01    1871 RC1    No       
##  3 allisar01   1871 CL1    No       
##  4 allisdo01   1871 WS3    No       
##  5 ansonca01   1871 RC1    No       
##  6 armstbo01   1871 FW1    No       
##  7 barkeal01   1871 RC1    No       
##  8 barnero01   1871 BS1    No       
##  9 barrebi01   1871 FW1    No       
## 10 barrofr01   1871 BS1    No       
## # … with 108,779 more rows</code></pre>
</div>
<div id="summarize" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Summarize</h3>
<p>The <code>summarize</code> command calculates summary statistics for all variables in the dataset.</p>
<p>The <code>n()</code> command returns the number of rows included in the summary.</p>
</div>
<div id="example-2.2.3" class="section level3 unnumbered">
<h3>Example 2.2.3</h3>
<p>Calculate the minimum, maximum, mean, median, and upper and lower quartiles for number stolen bases</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">min_SB =</span> <span class="kw">min</span>(SB), 
                      <span class="dt">Q1_SB =</span> <span class="kw">quantile</span>(SB, <span class="fl">0.25</span>),
                      <span class="dt">median_SB =</span> <span class="kw">median</span>(SB),
                      <span class="dt">Q3_SB =</span> <span class="kw">quantile</span>(SB, <span class="fl">0.75</span>), 
                      <span class="dt">max_SB =</span> <span class="kw">max</span>(SB), 
                      <span class="dt">mean_SB =</span><span class="kw">mean</span>(SB),
                      <span class="dt">Number =</span> <span class="kw">n</span>())</code></pre></div>
<pre><code>## Error: Problem with `summarise()` input `Q1_SB`.
## x missing values and NaN&#39;s not allowed if &#39;na.rm&#39; is FALSE
## ℹ Input `Q1_SB` is `quantile(SB, 0.25)`.</code></pre>
<p>The quantities we desire cannot be calculated some players have missing values. We tell R to ignore missing values using the argument <code>na.rm=TRUE</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">min_SB =</span> <span class="kw">min</span>(SB, <span class="dt">na.rm=</span><span class="ot">TRUE</span>), 
                      <span class="dt">Q1_SB =</span> <span class="kw">quantile</span>(SB, <span class="fl">0.25</span>, <span class="dt">na.rm=</span><span class="ot">TRUE</span>),
                      <span class="dt">median_SB =</span> <span class="kw">median</span>(SB, <span class="dt">na.rm=</span><span class="ot">TRUE</span>),
                      <span class="dt">Q3_SB =</span> <span class="kw">quantile</span>(SB, <span class="fl">0.75</span>, <span class="dt">na.rm=</span><span class="ot">TRUE</span>), 
                      <span class="dt">max_SB =</span> <span class="kw">max</span>(SB, <span class="dt">na.rm=</span><span class="ot">TRUE</span>), 
                      <span class="dt">mean_SB =</span><span class="kw">mean</span>(SB, <span class="dt">na.rm=</span><span class="ot">TRUE</span>),
                      <span class="dt">Number =</span> <span class="kw">sum</span>(<span class="op">!</span><span class="kw">is.na</span>(SB)))</code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   min_SB Q1_SB median_SB Q3_SB max_SB mean_SB Number
##    &lt;int&gt; &lt;dbl&gt;     &lt;int&gt; &lt;dbl&gt;  &lt;int&gt;   &lt;dbl&gt;  &lt;int&gt;
## 1      0     0         0     2    138    2.92 106421</code></pre>
</div>
<div id="practice-2.2.4" class="section level3 unnumbered">
<h3>Practice 2.2.4</h3>
<p>Create a variable to calculate each player's stolen base success proportion (SB/(SB+CS)).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Enter Code Here</span></code></pre></div>
</div>
<div id="practice-2.2.5" class="section level3 unnumbered">
<h3>Practice 2.2.5</h3>
<p>Calculate the minimum, maximum, mean, median, and upper and lower quartiles for humber hits. Also give the total number of players in the dataset.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Enter Code Here</span></code></pre></div>
</div>
<div id="example-2.2.6" class="section level3 unnumbered">
<h3>Example 2.2.6</h3>
<p>While overall summaries are sometimes useful, often it is far more useful to summarize by group. The <code>group_by</code> command allows us to calculate summary statistics broken down by group.</p>
<p>Calculate the number of homeruns (HR), hits (H), and at-bats (AB) for by each team, throughout baseball history.</p>
<p>When grouping, <code>n()</code> returns the number of observations in each group.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(teamID) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">HR =</span> <span class="kw">sum</span>(HR),
            <span class="dt">H=</span> <span class="kw">sum</span>(H), 
            <span class="dt">AB=</span> <span class="kw">sum</span>(AB),
            <span class="dt">Total_Player_Seasons =</span> <span class="kw">n</span>()
  ) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(HR))</code></pre></div>
<pre><code>## # A tibble: 149 x 5
##    teamID    HR      H     AB Total_Player_Seasons
##    &lt;fct&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;                &lt;int&gt;
##  1 NYA    16309 166924 626513                 4471
##  2 CHN    14449 194194 739897                 5060
##  3 DET    13904 169123 637722                 4413
##  4 BOS    13793 170584 638385                 4515
##  5 PHI    13321 187367 718794                 4971
##  6 CIN    13255 179875 688343                 4731
##  7 CLE    13228 168997 636579                 4683
##  8 SLN    12046 181892 682991                 4853
##  9 CHA    11606 164533 632007                 4476
## 10 PIT    11564 187060 706152                 4920
## # … with 139 more rows</code></pre>
<p>While we might be interested in knowing the number of total player seasons for each team, it might be more interesting to know the number of different batters who have played for each team. We can accomplish this using the <code>unique()</code> function. The command <code>unique(playerID)</code> creates a vector of unique player ID's for each team. The <code>length()</code> command returns the length of each vector (i.e. number of different batters).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(teamID) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">HR =</span> <span class="kw">sum</span>(HR),
            <span class="dt">H=</span> <span class="kw">sum</span>(H), 
            <span class="dt">AB=</span> <span class="kw">sum</span>(AB),
            <span class="dt">Total_Batters =</span> <span class="kw">length</span>(<span class="kw">unique</span>(playerID))
  ) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(HR))</code></pre></div>
<pre><code>## # A tibble: 149 x 5
##    teamID    HR      H     AB Total_Batters
##    &lt;fct&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;         &lt;int&gt;
##  1 NYA    16309 166924 626513          1709
##  2 CHN    14449 194194 739897          2117
##  3 DET    13904 169123 637722          1718
##  4 BOS    13793 170584 638385          1838
##  5 PHI    13321 187367 718794          2103
##  6 CIN    13255 179875 688343          1977
##  7 CLE    13228 168997 636579          1917
##  8 SLN    12046 181892 682991          2024
##  9 CHA    11606 164533 632007          1807
## 10 PIT    11564 187060 706152          1945
## # … with 139 more rows</code></pre>
</div>
<div id="example-2.2.7" class="section level3 unnumbered">
<h3>Example 2.2.7</h3>
<p>Calculate each team's all-time batting average. Include only teams with at least 100,000 at-bats. Sort by batting average.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(teamID) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">HR =</span> <span class="kw">sum</span>(HR),
            <span class="dt">H=</span> <span class="kw">sum</span>(H), 
            <span class="dt">AB=</span> <span class="kw">sum</span>(AB),
            <span class="dt">Total_Batters =</span> <span class="kw">length</span>(<span class="kw">unique</span>(playerID)),
            <span class="dt">AVG =</span> H <span class="op">/</span><span class="st"> </span>AB
  ) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(AB <span class="op">&gt;</span><span class="st"> </span><span class="dv">100000</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(AVG))</code></pre></div>
<pre><code>## # A tibble: 39 x 6
##    teamID    HR      H     AB Total_Batters   AVG
##    &lt;fct&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;         &lt;int&gt; &lt;dbl&gt;
##  1 COL     5013  41243 150606           593 0.274
##  2 NY1     5776 103368 381156           894 0.271
##  3 BOS    13793 170584 638385          1838 0.267
##  4 BRO     4338  93508 350213           875 0.267
##  5 NYA    16309 166924 626513          1709 0.266
##  6 SLN    12046 181892 682991          2024 0.266
##  7 PHA     3502  74209 278843           783 0.266
##  8 CLE    13228 168997 636579          1917 0.265
##  9 DET    13904 169123 637722          1718 0.265
## 10 PIT    11564 187060 706152          1945 0.265
## # … with 29 more rows</code></pre>
</div>
<div id="example-2.2.8" class="section level3 unnumbered">
<h3>Example 2.2.8</h3>
<p>Some of these teams do not exist anymore, while others came about more recently. Let's include the earliest and latest year that each team played.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(teamID) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">HR =</span> <span class="kw">sum</span>(HR),
            <span class="dt">H=</span> <span class="kw">sum</span>(H), 
            <span class="dt">AB=</span> <span class="kw">sum</span>(AB),
            <span class="dt">Total_Batters =</span> <span class="kw">length</span>(<span class="kw">unique</span>(playerID)),
            <span class="dt">AVG =</span> H <span class="op">/</span><span class="st"> </span>AB,
            <span class="dt">First_Year =</span> <span class="kw">min</span>(yearID),
            <span class="dt">Last_Year =</span> <span class="kw">max</span>(yearID)
  ) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(AB <span class="op">&gt;</span><span class="st"> </span><span class="dv">100000</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(AVG))</code></pre></div>
<pre><code>## # A tibble: 39 x 8
##    teamID    HR      H     AB Total_Batters   AVG First_Year Last_Year
##    &lt;fct&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;         &lt;int&gt; &lt;dbl&gt;      &lt;int&gt;     &lt;int&gt;
##  1 COL     5013  41243 150606           593 0.274       1993      2020
##  2 NY1     5776 103368 381156           894 0.271       1883      1957
##  3 BOS    13793 170584 638385          1838 0.267       1901      2020
##  4 BRO     4338  93508 350213           875 0.267       1890      1957
##  5 NYA    16309 166924 626513          1709 0.266       1903      2020
##  6 SLN    12046 181892 682991          2024 0.266       1892      2020
##  7 PHA     3502  74209 278843           783 0.266       1901      1954
##  8 CLE    13228 168997 636579          1917 0.265       1901      2020
##  9 DET    13904 169123 637722          1718 0.265       1901      2020
## 10 PIT    11564 187060 706152          1945 0.265       1887      2020
## # … with 29 more rows</code></pre>
</div>
<div id="example-2.2.9" class="section level3 unnumbered">
<h3>Example 2.2.9</h3>
<p>We can group by more than one variable. Let's calculate the number of hits, homeruns, and at-bats, and batting average for each team in each season.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batting <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(teamID, yearID) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">HR =</span> <span class="kw">sum</span>(HR),
            <span class="dt">H=</span> <span class="kw">sum</span>(H), 
            <span class="dt">AB=</span> <span class="kw">sum</span>(AB),
            <span class="dt">AVG =</span> H <span class="op">/</span><span class="st"> </span>AB
  ) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(HR))</code></pre></div>
<pre><code>## # A tibble: 2,955 x 6
## # Groups:   teamID [149]
##    teamID yearID    HR     H    AB   AVG
##    &lt;fct&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
##  1 MIN      2019   307  1547  5732 0.270
##  2 NYA      2019   306  1493  5583 0.267
##  3 HOU      2019   288  1538  5613 0.274
##  4 LAN      2019   279  1414  5493 0.257
##  5 NYA      2018   267  1374  5515 0.249
##  6 SEA      1997   264  1574  5614 0.280
##  7 TEX      2005   260  1528  5716 0.267
##  8 BAL      1996   257  1557  5689 0.274
##  9 OAK      2019   257  1384  5561 0.249
## 10 TOR      2010   257  1364  5495 0.248
## # … with 2,945 more rows</code></pre>
</div>
<div id="practice-2.2.10" class="section level3 unnumbered">
<h3>Practice 2.2.10</h3>
<p>Calculate the total number of at-bats (AB), hits (H), and homeruns (HR) for each player throughout their career. Also calculate their career batting average (H / AB). Sort the dataset from most hits to fewest.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Enter Code Here</span></code></pre></div>
</div>
<div id="practice-2.2.11" class="section level3 unnumbered">
<h3>Practice 2.2.11</h3>
<p>Calculate the total number of records (rows) for each player in the dataset. Order from most to least. Also include the player's first and last season. Note that some players played non-consecutive seasons, so the number of records will not necessarily equal the difference between the first and last seasons.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Enter Code Here</span></code></pre></div>
</div>
<div id="practice-2.2.12" class="section level3 unnumbered">
<h3>Practice 2.2.12</h3>
<p>The total number of records for each player is not quite equal to their total number of seasons played, since players sometimes play for more than one team in a season. Calculate the total number of seasons played by each player.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Enter Code Here</span></code></pre></div>
</div>
<div id="practice-2.2.13" class="section level3 unnumbered">
<h3>Practice 2.2.13</h3>
<p>Calculate the average number of stolen bases and homeruns per team for each year since 1871. For example, the average number of homeruns per team was 226.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Enter Code Here</span></code></pre></div>
<p>Plot the average number of homeruns and stolen bases against year.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Enter Code Here</span></code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Enter Code Here</span></code></pre></div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-visualization.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/DSP-LU-W22/DSP-W22-Notes/edit/master/02-Data_Wrangling.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/DSP-LU-W22/DSP-W22-Notes/blob/master/02-Data_Wrangling.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
